/**
 * Renderers for every generated artifact, plus the staleness check the doctor reuses (S-35, S-36).
 *
 * One module so `generate-env`, `generate-docs` and `mcp-doctor` cannot disagree about what the
 * current content should be. The doctor's job is to notice that a committed file no longer matches
 * the manifest, and it can only do that by rendering the same bytes the writer would.
 */

import fs from "node:fs";
import path from "node:path";

import { SERVERS, WORKSPACE_ROOT } from "./manifest.mjs";

/** Markers delimiting a generated region inside an otherwise hand-written file. */
const BEGIN = (id) => `<!-- BEGIN GENERATED: ${id} -->`;
const END = (id) => `<!-- END GENERATED: ${id} -->`;

/** Sections in first-appearance order — the generated file should read like a human wrote it. */
function sectionsOf(server) {
  const order = [];
  const groups = new Map();
  for (const field of server.env) {
    const key = field.section ?? "Configuration";
    if (!groups.has(key)) {
      groups.set(key, []);
      order.push(key);
    }
    groups.get(key).push(field);
  }
  return order.map((title) => ({ title, fields: groups.get(title) }));
}

/**
 * Wrap a note at ~76 chars as `#` comment lines.
 *
 * Long single-line comments are the reason people stop reading .env files.
 */
function commentLines(text, width = 76) {
  const words = String(text).split(/\s+/);
  const lines = [];
  let line = "";
  for (const word of words) {
    if (line !== "" && (line + " " + word).length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line === "" ? word : `${line} ${word}`;
    }
  }
  if (line !== "") lines.push(line);
  return lines.map((l) => `# ${l}`);
}

function pad(title) {
  const head = `# --- ${title} `;
  return head + "-".repeat(Math.max(0, 78 - head.length));
}

/**
 * Render a server's `.env.example`.
 *
 * A field is emitted ACTIVE (`KEY=value`) when the installer would write it — i.e. it has a
 * `default` or a `prompt`. Everything else is emitted COMMENTED (`# KEY=`), because writing a
 * tuning knob into a real .env pins it at today's value and it silently stops tracking the code.
 * That distinction is the whole reason `codeDefault` exists separately from `default`.
 */
export function renderEnvExample(server) {
  const out = [
    `# ${server.dir} — environment configuration`,
    "#",
    "# @generated by scripts/generate-env.mjs from @mcp/manifest — do not edit by hand.",
    "# Run `npm run generate:env` after changing the manifest; `npm run generate:check` fails on drift.",
    "#",
    "# Copy the values you need into the `env` block of your ~/.claude.json server entry (or a",
    "# local .env when running `npm run dev`). Never commit real secrets.",
    "#",
    "# Uncommented lines are what the installer writes for you. Commented lines are tuning knobs:",
    "# the value shown is the server's own fallback, so setting one PINS it — leave it alone unless",
    "# you mean to override."
  ];

  for (const { title, fields } of sectionsOf(server)) {
    out.push("", pad(title));
    for (const field of fields) {
      if (field.note) out.push(...commentLines(field.note));
      // A renamed var must say so where an operator will actually look. Without this the old name
      // still works but is undiscoverable, so the deprecation never completes.
      if (field.deprecatedAliases?.length) {
        out.push(...commentLines(`Renamed. Still accepts: ${field.deprecatedAliases.join(", ")}.`));
      }
      if (field.prefix !== undefined) {
        // Never emit the wildcard as if it were assignable — `PG_ENV_*=` invites someone to set
        // it literally, which satisfies nothing. Show the real member names instead.
        const members = field.familyExamples ?? [`${field.prefix}DEV`];
        out.push(...members.map((name) => `# ${name}=`), "");
        continue;
      }
      const active = field.default !== undefined || field.prompt !== undefined;
      if (active) {
        out.push(`${field.name}=${field.secret === true ? "" : (field.default ?? "")}`);
      } else {
        out.push(`# ${field.name}=${field.codeDefault ?? ""}`);
      }
      out.push("");
    }
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

const esc = (s) => String(s).replaceAll("|", "\\|");

/** Markdown env table for a README's generated block. */
export function renderEnvTable(server) {
  const rows = server.env.map((field) => {
    const req = field.required ? "**yes**" : field.group ? `one of \`${field.group}\`` : "no";
    const dflt = field.default !== undefined && field.default !== ""
      ? `\`${esc(field.default)}\``
      : field.codeDefault !== undefined
        ? `\`${esc(field.codeDefault)}\` *(code)*`
        : "—";
    const notes = [
      field.secret === true ? "**secret**" : null,
      field.deprecatedAliases?.length
        ? `renamed — still accepts \`${field.deprecatedAliases.join("`, `")}\``
        : null,
      field.note ? esc(field.note) : null
    ]
      .filter(Boolean)
      .join(" · ");
    return `| \`${field.name}\` | ${req} | ${dflt} | ${notes || "—"} |`;
  });
  return [
    "| Variable | Required | Default | Notes |",
    "|---|---|---|---|",
    ...rows,
    "",
    `${server.env.length} variables. Defaults marked *(code)* are the server's own fallback and are **not** written into your agent config — set them only to override.`
  ].join("\n");
}

/** Markdown tool list for a README's generated block. */
export function renderToolList(server) {
  return [
    `${server.tools.length} tools, namespaced \`mcp__${server.key}__<tool>\`:`,
    "",
    ...server.tools.map((t) => `- \`${t}\``)
  ].join("\n");
}

/**
 * Replace the content between markers, leaving everything else byte-identical.
 *
 * Returns null when the file has no marker pair for `id`, so a README that has not opted in is
 * left alone rather than being rewritten wholesale.
 */
export function spliceBlock(content, id, body) {
  const begin = content.indexOf(BEGIN(id));
  const end = content.indexOf(END(id));
  if (begin === -1 || end === -1 || end < begin) return null;
  const head = content.slice(0, begin + BEGIN(id).length);
  const tail = content.slice(end);
  return `${head}\n\n${body}\n\n${tail}`;
}

export function hasBlock(content, id) {
  return content.includes(BEGIN(id)) && content.includes(END(id));
}

/** Every generated target: `{ file, next }` with `next` the content it should hold. */
export function generatedTargets() {
  const targets = [];

  for (const server of SERVERS) {
    targets.push({
      file: path.join(WORKSPACE_ROOT, server.dir, ".env.example"),
      next: renderEnvExample(server),
      kind: "env"
    });

    const readme = path.join(WORKSPACE_ROOT, server.dir, "README.md");
    if (!fs.existsSync(readme)) continue;
    let content = fs.readFileSync(readme, "utf8");
    let touched = false;
    for (const [id, body] of [
      ["env-table", renderEnvTable(server)],
      ["tool-list", renderToolList(server)]
    ]) {
      const spliced = spliceBlock(content, id, body);
      if (spliced !== null) {
        content = spliced;
        touched = true;
      }
    }
    if (touched) targets.push({ file: readme, next: content, kind: "docs" });
  }

  return targets;
}

/** Compare on disk vs rendered, newline-insensitively (the repo checks out CRLF on Windows). */
export function staleTargets(kind = null) {
  const stale = [];
  for (const target of generatedTargets()) {
    if (kind !== null && target.kind !== kind) continue;
    const current = fs.existsSync(target.file) ? fs.readFileSync(target.file, "utf8") : null;
    const same = current !== null && current.replace(/\r\n/g, "\n") === target.next.replace(/\r\n/g, "\n");
    if (!same) stale.push({ ...target, missing: current === null });
  }
  return stale;
}

export function writeTargets(kind = null) {
  const written = [];
  for (const target of staleTargets(kind)) {
    fs.writeFileSync(target.file, target.next, "utf8");
    written.push(path.relative(WORKSPACE_ROOT, target.file));
  }
  return written;
}
