#!/usr/bin/env node
/**
 * Derive each server's tool list into `packages/manifest/src/generated/toolLists.ts` (S-36).
 *
 * Before this, `tools:` was hand-maintained in the manifest and had already drifted —
 * `codebase-index-local` named 12 of its 43 tools, so the generated skill advertised a third of
 * the server. Nothing detected that, because nothing compared the list to the server.
 *
 * The source is `contracts/<key>.json`: the committed `tools/list` snapshot, captured from a real
 * stdio handshake and verified in CI by `contracts:check`. Reading the snapshot rather than
 * booting the servers again keeps this script free of a build dependency — which matters, because
 * the file it writes is compiled INTO the manifest that a boot would need.
 *
 *   node scripts/generate-tools.mjs [--check]
 */

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "..");
const CONTRACTS = path.join(ROOT, "contracts");
const TARGET = path.join(ROOT, "packages", "manifest", "src", "generated", "toolLists.ts");
const CHECK = process.argv.includes("--check");

function render() {
  const files = fs
    .readdirSync(CONTRACTS)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    throw new Error("contracts/ holds no snapshots — run `npm run contracts:update` first");
  }

  const entries = files.map((file) => {
    const key = path.basename(file, ".json");
    const snapshot = JSON.parse(fs.readFileSync(path.join(CONTRACTS, file), "utf8"));
    const tools = (snapshot.tools ?? []).map((t) => t.name).sort();
    if (tools.length === 0) throw new Error(`${file}: snapshot lists no tools`);
    // The snapshot records its own count; disagreeing with it means the file was hand-edited.
    if (typeof snapshot.toolCount === "number" && snapshot.toolCount !== tools.length) {
      throw new Error(`${file}: toolCount ${snapshot.toolCount} but ${tools.length} tools listed`);
    }
    return { key, tools };
  });

  const total = entries.reduce((n, e) => n + e.tools.length, 0);
  const body = entries
    .map(({ key, tools }) => {
      const list = tools.map((t) => `    "${t}"`).join(",\n");
      return `  ${JSON.stringify(key)}: [\n${list}\n  ]`;
    })
    .join(",\n\n");

  return `// @generated by scripts/generate-tools.mjs from contracts/ — do not edit by hand.
// Run \`npm run generate:tools\` after an intended tool change; \`npm run generate:check\` fails on drift.
//
// ${total} tools across ${entries.length} servers. The source is the committed tools/list
// snapshots, which CI verifies against the running servers via \`contracts:check\`.

export const TOOL_LISTS: Readonly<Record<string, readonly string[]>> = {
${body}
};

/** Total advertised tools across every server — asserted by the manifest's tests. */
export const TOTAL_TOOL_COUNT = ${total};
`;
}

const next = render();
const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8") : null;
const same = current !== null && current.replace(/\r\n/g, "\n") === next.replace(/\r\n/g, "\n");

if (CHECK) {
  if (same) {
    console.log("generate:tools — up to date");
    process.exit(0);
  }
  console.error(
    `STALE  ${path.relative(ROOT, TARGET)}\n` +
      "       Tool lists no longer match contracts/. Run `npm run generate:tools` and commit."
  );
  process.exit(1);
}

if (same) {
  console.log("generate:tools — no change");
} else {
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, next, "utf8");
  console.log(`generate:tools — wrote ${path.relative(ROOT, TARGET)}`);
}
